### ISSUE TITLE
Need to speed up serialization / deserialization of results objects

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#533]
It would take 4 minutes just do to 1,000 observations
<img width="604" alt="Screenshot 2024-05-20 at 4 48 41 PM" src="https://github.com/expectedparrot/edsl/assets/407218/27a11cf3-5497-43d2-b5e4-a5fe0aabfd36">

**Comment by johnjosephhorton** [comment]
Existing `edsl/__init__.py` is a huge bottleneck:

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    11                                           def profile_import():
    12         1    1402208.0    1e+06    100.0      from edsl.results.Result import Result

(edsl-py3.10) john@Johns-MacBook-Air edsl % rm edsl/__init__.py 
(edsl-py3.10) john@Johns-MacBook-Air edsl % python profile_edsl_import.py
Timer unit: 1e-06 s

Total time: 0.000574 s
File: /Users/john/tools/edsl/profile_edsl_import.py
Function: profile_import at line 11

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    11                                           def profile_import():
    12         1        574.0    574.0    100.0      from edsl.results.Result import Result

(edsl-py3.10) john@Johns-MacBook-Air edsl % 
```

**Comment by zer0dss** [comment]
@johnjosephhorton The bottleneck is present in the LanguageModel.from_dict part. Each time there is a call to the OpenAI API. As can be seen here, the execution time for one result.from_dict is divided as follows:

agent.from_dict execution: 4.029273986816406e-05 seconds
scenario_from_dict execution: 1.0967254638671875e-05 seconds
**language_model_from_dict execution: 0.3074038028717041 seconds**
**Total result.from_dict execution: 0.3076903820037842 seconds**

The bottleneck is caused by the calls to this method: [Available method on GitHub](https://github.com/expectedparrot/edsl/blob/e23d34cc5d232040d92ab619b4f2a8024eb1b8c5/edsl/inference_services/OpenAIService.py#L33C9-L33C18). And the call stack to reach it is this one:
**Results.from_dict -> Result.from_dict -> LanguageModel.from_dict -> get_model_class -> create_model_factory -> service.available -> openai call.**

**Comment by johnjosephhorton** [comment]
This is awesome @zer0dss - I know you're working on a bunch of stuff w/ @apostolosfilippas but to extent you have bandwidth to profile code and spot bottlenecks, I'd love your help
