### ISSUE TITLE
Session-setting Cache doesn't seem to be working?

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#611]
![Screenshot from 2024-06-06 09-46-49](https://github.com/expectedparrot/edsl/assets/407218/5a093bf4-1d64-4ad4-9ded-a6c94082ebea)
![Screenshot from 2024-06-06 09-46-12](https://github.com/expectedparrot/edsl/assets/407218/9562135b-e391-495a-ad19-e6c80ad11a86)
![Screenshot from 2024-06-06 09-46-18](https://github.com/expectedparrot/edsl/assets/407218/d3a4f6c5-6dfe-4512-9573-52df6a5a8699)
![Screenshot from 2024-06-06 09-46-36](https://github.com/expectedparrot/edsl/assets/407218/0249bfab-9bff-416e-a15f-4924f1dc4d9a)

**Comment by zer0dss** [comment]
@johnjosephhorton I think this happens because inside the CacheHandler __init__ constructor there is no check if the global **_CACHE** is already defined. When a Job is created there is a call to  [CacheHandler().get_cache()](https://github.com/expectedparrot/edsl/blob/452cdeb3f68e6fb723963d1495290b65918470b4/edsl/jobs/Jobs.py#L338)  that calls the constructor and creates the cache directory without checking for **_CACHE** global variable.
