### ISSUE TITLE
Programmatically get token prices

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#859]
[ Will add details -- hold for now ]

**Comment by johnjosephhorton** [comment]
so @zer0dss as you saw, @rbyh has a spreadsheet that lists prices. What I think we want to do is: 
1. Re-factor this "fetch_prices" function to instead make a call to coop
2. Have coop draw from this spreadsheet instead, at least for now. Longer-term, we might create an interface. 
3. Have the edsl code that estimates costs actually use these prices

**Comment by apostolosfilippas** [comment]
Shouldn't we just have those in a yaml instead of having a call? Coop can just access a local file to calculate + this can also be use in price pages

**Comment by johnjosephhorton** [comment]
Not opposed, but I'd rather than have to run do a PR & edit a YAML every time we want to change prices, add new models, etc. I was thinking longer-term we'd have an admin view in coop that would let us change things there, but as a short-term fix. I also don't think we'd fetch it frequently - I was imagining something with a LRU decorator with re-fetch prices that expire like 6 hours or so. Could also just read from a YAML that that some service writes to periodically.

**Comment by johnjosephhorton** [comment]
I think this has been superceded by other things, but an admin pricing page should be part of our larger "get ready for more users" planning, @rbyh
