### ISSUE TITLE
Question instructions not passing through

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#888]
Hi - I think there is also a problem for free text questions. It's impossible to override `instructions` for these and it always returns the default instructions.
The code in QuestionBase is a little indirect but it seems like the issue is there?

(thanks for quick reply btw, and for the library. it's proving very useful)

_Originally posted by @benwhalley in https://github.com/expectedparrot/edsl/issues/866#issuecomment-2293486338_

**Comment by johnjosephhorton** [comment]
@rbyh can you produce the error and then assign issue to me to fix?

**Comment by benwhalley** [comment]
```
topics = ScenarioList([Scenario({"topic": i}) for i in ["dogs", "cats"]])
myq = QuestionFreeText(
    question_name = "joke",
    question_text = "tell me a joke about {{topic}}",
    instructions="just free text don't use json")


jobs = (
    myq.by(topics)
)
jobs.prompts().to_pandas()['user_prompt'][0]
```


this still produces 

```
You are being asked the following question: tell me a joke about dogs\nReturn a valid JSON formatted like this:\n{"answer": "<put free text answer here>"}'
```


Weirdly, even if you subclass QuestionFreeText and override `default_instructions` the same default string is used.

**Comment by benwhalley** [comment]
For context, I want to use the QuestionFreeText  to return json in a different format. I get a lot of errors currently because the json format I want doesn't have an 'answer' and 'explanation' key.

Perhaps it would be worth having a QuestionJson or QuestionStruct type? Ideally you would be able to pass in a pydantic object spec as the instruction and it would instruct the model and parse the result?

**Comment by rbyh** [comment]
Looking into this!

There is `QuestionExtract` which can be used more flexibly to specify the form of the output with an example (you may have to fiddle around with examples in the answer template).

https://docs.expectedparrot.com/en/latest/questions.html#questionextract-class

https://docs.expectedparrot.com/en/latest/notebooks/question_extract_example.html

**Comment by johnjosephhorton** [comment]
Oh I think I know what it is - we moved it out of the constructor and made adding instructions model-specific, as a method. 

This is a method of QuestionBase, so all questions should take this kind of over-rider:

<img width="1183" alt="Screenshot 2024-08-16 at 9 50 33 AM" src="https://github.com/user-attachments/assets/952c85bd-1f73-406c-8a83-ee3ceff80d86">

**Comment by johnjosephhorton** [comment]
In terms of 'why' - we wanted to allow the user to specify instructions on a model-by-model basis rather than one 'fixed' attribute. Note that if you pass "None" it will update for all models

**Comment by rbyh** [comment]
Thanks so much for raising this @benwhalley

**Comment by benwhalley** [comment]
Cool. Glad it's helpful. As a request, I can see why adding model specific instructions would be helpful, but it would be nice to be able to pass in generic instructions for all models too. 

Perhaps instructions could either be a single string or a dictionary where keys are model names or substrings for model names. 

So you could have a key 'gpt-4' for example and it would be used for all the models starting gpt-4

Without something like this you might end up tying the questions to specific model instances in an annoying way. 

Also - definitely worth adding some docs on the instructions and model instructions. It's quite opaque what the final prompt will be at the moment (eg where persona and instructions will end up). 

Finally! I also wondered how useful you thought it was to separate the system and user messages? In my experience it doesn't make a difference, and is simpler to have a single template for the whole prompt. It would be nice, for example, to be able to just override where {persona} gets dropped. Conceptually persona doesn't seem different to scenario, except that it is special cased in the prompting?

**Comment by johnjosephhorton** [comment]
Thanks - so I *think* if you leave the model blank, that instruction will supercede everything. But it could also in principle use wildcards. This might be nice.

re: control over prompts - indeed. I started making this more programmable but haven't documented this yet. It will let you decide what you want to go in the system prompt versus user prompt etc. If you're interested, it's in: 

https://github.com/expectedparrot/edsl/blob/main/edsl/agents/PromptConstructionMixin.py

**Comment by benwhalley** [comment]
QuestionExtract could be nice, but I think there seems to be a general confusion about the role of the prompt vs the magic that happens to try and coerce an answer in the right format and parse the result.

For example, QuestionExtract  includes both instructions to follow the format in `answer_template={...}` AND a final instruction to 

```
Return a valid JSON formatted like this:
{"answer": <put your ANSWER here>}
ONLY RETURN THE JSON, AND NOTHING ELSE.
```
This confuses the model.

In general, I think the `instructions` field would really need to turn off all other adaptations made to the user prompt because it's likely to be used when those defaults aren't working well.





FWIW I think it would be helpful to either do less magic or more. The `magentic` library is nice because it allows you to specify a Pydantic model to specify the output format, and validate the return value. But this won't work with non-openai models at the moment.

**Comment by rbyh** [comment]
Agreed! @johnjosephhorton is making some big improvements to instructions right now -- thanks for the inspiration :)

In the meantime, you can also use `QuestionList` flexibly to specify differently formatted responses. Eg, if you want a dictionary you can (loosely, even) describe it and clarify that it will be the single item in the list:
<img width="981" alt="image" src="https://github.com/user-attachments/assets/3ae5f36f-2d4c-4088-a1e5-dfaf1520e9f1">
